version = 1

[[annotations]]
path = ["src/**"]
SPDX-FileCopyrightText = "Rodolphe Bréard"
SPDX-License-Identifier = "CECILL-C OR CECILL-2.1"

[[annotations]]
path = [
    ".forgejo/**",
    ".gitignore",
    "Cargo.toml",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "deny.toml",
    "Makefile",
    "README.md",
    "release.toml",
    "REUSE.toml",
    "rustfmt.toml",
    "tests/Makefile"
]
SPDX-FileCopyrightText = "Rodolphe Bréard"
SPDX-License-Identifier = "CC0-1.0"
