name: periodic
on:
  schedule:
    - cron: '25 3 1,16 * *'

jobs:
  test:
    name: Cargo build
    runs-on: codeberg-tiny
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - name: Download rustup install script
        run: curl --proto '=https' --tlsv1.2 --output 'rustup_install.sh' -sSf https://sh.rustup.rs && chmod a+x 'rustup_install.sh'
      - name: Install rustup
        run: ./rustup_install.sh -y
      - name: Install Rust ${{ matrix.rust }}
        run: source "$HOME/.cargo/env" && rustup toolchain install ${{ matrix.rust }}
      - name: Run cargo build
        run: source "$HOME/.cargo/env" && cargo +${{ matrix.rust }} build --all-features --verbose
  cargo-deny:
    name: Check dependencies
    runs-on: codeberg-tiny
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - name: Download rustup install script
        run: curl --proto '=https' --tlsv1.2 --output 'rustup_install.sh' -sSf https://sh.rustup.rs && chmod a+x 'rustup_install.sh'
      - name: Install rustup
        run: ./rustup_install.sh -y
      - name: Install cargo-deny
        run: source "$HOME/.cargo/env" && cargo install --locked cargo-deny
      - name: Run cargo-deny
        run: source "$HOME/.cargo/env" && cargo deny --all-features check
